### ISSUE TITLE
Add GitLab Mylyn Connector

### ISSUE THREAD

**Issue by smoyer64** [selesy/workstation#13]
Fix the security issue identified by Seltzer.

**Comment by StephenSeltzer** [comment]
In order to get issue tracking from GitLab to be available in Eclipse via mylyn I needed to add the unlimited security policy. Reference Service Now incident number INC0246333.

When attempting to add a task repository in Eclipse, I receive notice:  Invalid TLS Certificate: Received fatal alert: handshake_failure message when attempting to connect Eclipse tasks to GitLab Issues task repository.

From help desk:
Ok, it looks like we're enforcing AES-256 in gitlab's SSL config. So you'll need to install the unlimited strength JCE provider to get AES-256. If you download it from http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html and follow the installation instructions it should work.
